#!/usr/bin/env bash
# Generate Markdown API reference from Go doc comments and write it into
# the Starlight content collection at docs/src/content/docs/reference/.
# Each generated file gets a Starlight frontmatter block prepended.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd)"
OUT_DIR="$ROOT_DIR/docs/src/content/docs/reference"
TMP_DIR="$(mktemp -d -t grx-gomarkdoc.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

GOMARKDOC_PKG="${GOMARKDOC_PKG:-github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest}"

cd "$ROOT_DIR"

go run "$GOMARKDOC_PKG" \
    --output "$TMP_DIR/{{.Dir}}/index.md" \
    ./core/... ./pkg/... ./schema/... ./exec/... ./server/... ./plugin/...

# Wipe out only the auto-generated package directories so a hand-written
# reference/index.md (the section landing page) is preserved.
for sub in core pkg schema exec server plugin; do
    rm -rf "$OUT_DIR/$sub"
done

mkdir -p "$OUT_DIR"

while IFS= read -r -d '' src; do
    rel="${src#"$TMP_DIR"/}"
    pkg_path="${rel%/index.md}"
    dst="$OUT_DIR/$rel"
    mkdir -p "$(dirname "$dst")"

    {
        echo "---"
        echo "title: ${pkg_path}"
        echo "description: API reference for the ${pkg_path} package, generated from Go doc comments."
        echo "tableOfContents:"
        echo "  minHeadingLevel: 2"
        echo "  maxHeadingLevel: 4"
        echo "editUrl: false"
        echo "---"
        echo
        # Drop the leading "Code generated by gomarkdoc" comment and the
        # immediate "# <pkg>" heading; Starlight already renders the title
        # from frontmatter.
        awk '
            BEGIN { skipped_header = 0 }
            !skipped_header && /^<!-- Code generated by gomarkdoc/ { next }
            !skipped_header && /^# / { skipped_header = 1; next }
            { print }
        ' "$src"
    } > "$dst"
done < <(find "$TMP_DIR" -type f -name 'index.md' -print0)

echo "Wrote API reference to $OUT_DIR"
